stages:
  - build
  - test
  - deploy
  - cleanup


before_script:
  - export ISOLATION=buildref${CI_BUILD_REF}$(echo ${CI_BUILD_REF_NAME} | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')
  - export COMPOSE_PROJECT_NAME=${ISOLATION}
  - export APP_VERSION=$(git describe --always --dirty)
  - export STACK_PHP_IMAGE=dmstr/yii2-app:${APP_VERSION}


build:
  stage: build
  script:
    - cp .env-dist .env
    - docker-compose build --pull

test:
  stage: test
  script:
    - cd tests
    - cp .env-dist .env
    - docker-compose run -e YII_ENV=test php codecept run

release:
  stage: deploy
  script:
    - docker push ${STACK_PHP_IMAGE}
  only:
    - release

cleanup:
  stage: cleanup
  when: always
  script:
    - docker-compose kill
    - docker-compose rm -fv --all
    - docker-compose down --remove-orphans --rmi local

